version: "3"
services:
  algo_app:
    container_name: myc
    build: .
    volumes:
      - ./../ml_vol:/opt/ml_vol
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 15G
    command: tail -f /dev/null # keep the container running
